import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [userInput, setUserInput] = useState("");
  const [output, setOutput] = useState("");
  const [outputTitle, setOutputTitle] = useState("");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-screen flex justify-center flex-col items-center p-4">
        <h1 className="text-3xl">Generator API</h1>
        <div className="max-w-sm mx-auto flex flex-col">
          <form
            onSubmit={(e) => {
              e.preventDefault();
              generatePoem();
            }}
            className="flex flex-row gap-x-4 my-8 justify-center"
          >
            <input
              value={userInput}
              onChange={(e) => setUserInput(e.target.value)}
              className="rounded-lg px-3 py-2 text-lg border"
              type="text"
              placeholder="Subject matter"
            ></input>
            <button
              type="submit"
              className="border text-lg px-3 py-2 bg-black text-white rounded-lg"
            >
              Submit
            </button>
          </form>
          <div className="text-sm whitespace-pre-line">
            <h1 class="text-lg">{outputTitle}</h1>
          </div>
          <div className="text-sm whitespace-pre-line">{output}</div>
        </div>
      </main>
    </>
  );

  async function generatePoem() {
    const response = await fetch("/api/generate-poem", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        input: userInput,
      }),
    });
    const data = await response.json();
    if (data.poem) {
      setOutput(data.poem);
      setOutputTitle(userInput);
    }
    setUserInput("");
  }
}
